### ISSUE TITLE
Bricked after upgrade: Need help

### ISSUE THREAD

**Issue by vonsete** [solokeys/solo#497]
Hi guys  
Today I have upgraded my SOMU Key. 
After the upgrade it looks bricked (it is not detected by the computer, and it does not blink) 

The logs are:  

_venv) alfonso@mediacenter:~/github/solo/targets/stm32l432$ cd ../.. 
(venv) alfonso@mediacenter:~/github/solo$ solo program aux enter-bootloader 
Solo rebooted. 
Reconnecting... Not using FIDO2 interface. (venv) 
alfonso@mediacenter:~/github/solo$ solo program bootloader targets/stm32l432/solo.hex 
Not using FIDO2 interface. 
erasing firmware... updated firmware 100% time: 2.22 s 
(venv) alfonso@mediacenter:~/github/solo$ solo program aux enter-bootloader 
Traceback (most recent call last): File "/home/alfonso/github/solo/venv/bin/solo", line 8, in sys.exit(solo_cli()) File "/home/alfonso/github/solo/venv/lib/python3.7/site-packages/click/core.py", line 829, in __call__ return self.main(*args, **kwargs) File "/home/alfonso/github/solo/venv/lib/python3.7/site-packages/click/core.py", line 782, in main rv = self.invoke(ctx) File "/home/alfonso/github/solo/venv/lib/python3.7/site-packages/click/core.py", line 1259, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) File "/home/alfonso/github/solo/venv/lib/python3.7/site-packages/click/core.py", line 1259, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) File "/home/alfonso/github/solo/venv/lib/python3.7/site-packages/click/core.py", line 1259, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) File "/home/alfonso/github/solo/venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke return ctx.invoke(self.callback, **ctx.params) File "/home/alfonso/github/solo/venv/lib/python3.7/site-packages/click/core.py", line 610, in invoke return callback(*args, **kwargs) File "/home/alfonso/github/solo/venv/lib/python3.7/site-packages/solo/cli/program.py", line 219, in enter_bootloader return _enter_bootloader(serial) File "/home/alfonso/github/solo/venv/lib/python3.7/site-packages/solo/cli/program.py", line 200, in _enter_bootloader p = solo.client.find(serial) File "/home/alfonso/github/solo/venv/lib/python3.7/site-packages/solo/client.py", line 53, in find raise solo.exceptions.NoSoloFoundError("no Solo found") solo.exceptions.NoSoloFoundError: no Solo found_  

What can I do? Please help me.
--

**Comment by JeffResc** [comment]
Hello, I'm new to Solo Keys, but I was just reading the documentation and thought this might be useful to you:

"It is safe to develop for Solo using our Solo bootloader. If broken firmware is uploaded to the device, then the Solo bootloader can always be booted again by holding down the button when plugging in."

As long as the bootloader still launches successfully, this should work, so it's worth a shot. Let me know.

You can read the rest of it here: https://docs.solokeys.dev/bootloader-mode/
