### ISSUE TITLE
make-credential ClientError "PIN required but not provided"

### ISSUE THREAD

**Issue by MarcinWieczorek** [solokeys/solo#566]
`solo key make-credential` returns this error
It doesn't matter if I leave it empty, enter the device's pin or any other combination. 
```
PIN (leave empty for no PIN):
Touch your authenticator to generate a credential...
Traceback (most recent call last):
  File "/sbin/solo", line 8, in <module>
    sys.exit(solo_cli())
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/solo/cli/key.py", line 151, in make_credential
    solo.hmac_secret.make_credential(
  File "/usr/lib/python3.9/site-packages/solo/hmac_secret.py", line 42, in make_credential
    attestation_object = client.make_credential(
  File "/usr/lib/python3.9/site-packages/fido2/client.py", line 455, in make_credential
    att_obj, extension_outputs = self._do_make_credential(
  File "/usr/lib/python3.9/site-packages/fido2/client.py", line 503, in _ctap2_make_credential
    raise ClientError.ERR.BAD_REQUEST("PIN required but not provided")
fido2.client.ClientError: (<ERR.BAD_REQUEST: 2>, 'PIN required but not provided')
```

**Comment by MarcinWieczorek** [comment]
duplicate of https://github.com/solokeys/solo-python/issues/134 I searched in wrong repo!
